### PR TITLE
Put Bot Code in  /src

### PR DESCRIPTION
**Pull request by Hidden-black**
Bot Code has Been moved To /src so the repo looks cleaner

### CODE REVIEW

**Comment by Hidden-black** [comment]
Added 2 Badges To readme 
Clicking The discord Icon takes you to server

**Comment by Hidden-black** [comment]
Removed Fonts
Edited Readme

**Comment by Hidden-black** [comment]
Test

**Comment by Prakhar9206** [comment]
Can you open this pull request on the dev branch pls?

**Pull request closed without merging**
